plugins:
  nested_replies_enabled:
    default: false
    client: true

  nested_replies_posts_per_page:
    default: 20
    min: 10
    max: 50

  nested_replies_max_initial_replies:
    default: 3
    min: 3
    max: 50

  nested_replies_load_more_count:
    default: 10
    min: 3
    max: 50
